dist: focal
language: python


python:
  - "3.8"

node_js:
  - node

cache:
  pip: true
  npm: true

install:
  - npm install
  - npm install -g serverless
  - pip install -r requirements.txt

script:
  - python -m unittest discover -vb tests/

