os: linux
dist: focal
language: node_js

node_js:
  - node

cache:
  npm: true

install:
  - npm install newman

before_script:
  - node_modules/.bin/newman --version

script:
  - npx newman run "tests/Leaf API.postman_collection.json" -e "tests/Leaf API.postman_environment.json"
